apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
controllerManager:
  extraArgs:
    flex-volume-plugin-dir: /etc/kubernetes/kubelet-plugins/volume/exec
nodeRegistration:
  kubeletExtraArgs:
    volume-plugin-dir: /etc/kubernetes/kubelet-plugins/volume/exec
networking:
  podSubnet: 10.244.0.0/16
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  criSocket: unix:///var/run/crio/crio.sock
  taints: []
skipPhases:
  - addon/kube-proxy
