apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    kubernetes.io/service-name: {{ .Values.name }}
    endpointslice.kubernetes.io/managed-by: cluster-admins
addressType: IPv4
endpoints:
  - addresses:
      - {{ .Values.address }}
ports:
{{- range $name, $config := .Values.ports }}
  - name: {{ $name }}
    protocol: {{ $config.protocol }}
    port: {{ $config.port }}
{{- end }}
