apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
  ports:
    {{- range $name, $config := .Values.ports }}
    - name: {{ $name }}
      protocol: {{ $config.protocol }}
      port: {{ $config.port }}
      targetPort: {{ $config.port }}
    {{- end }}