apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "app.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.env }}
          env:
            {{- range $name, $value := . }}
            - name: {{ $name }}
              value: {{ $value }}
            {{- end }}
          {{- end }}
          {{- if gt (len .Values.ports) 0 }}
          ports:
            {{- range $name, $port := .Values.ports }}
            - name: {{ $name }}
              protocol: {{ $port.protocol }}
              containerPort: {{ $port.containerPort }}
            {{- end }} 
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.dri .Values.volumes.localTime (gt (len .Values.volumes.persistent) 0) }}
          volumeMounts:
            {{- if .Values.volumes.dri }}
            - name: dev-dri
              mountPath: /dev/dri
              readOnly: true
            {{- end }}
            {{- if .Values.volumes.localTime }}
            - name: etc-localtime
              mountPath: /etc/localtime
              readOnly: true
            {{- end }}
            {{- range $name, $config := .Values.volumes.persistent }}
            - name: {{ $name }}
              mountPath: {{ $config.mountPath }} 
              {{- if $config.readOnly }}
              readOnly: {{ $config.readOnly }}
              {{- end }}
            {{- end }}
          {{- end }}
      {{- if or .Values.dri .Values.volumes.localTime (gt (len .Values.volumes.persistent) 0) }}
      volumes:
        {{- if .Values.volumes.dri }}
        - name: dev-dri
          hostPath:
            path: /dev/dri
            type: Directory
        {{- end }}
        {{- if .Values.volumes.localTime }}
        - name: etc-localtime
          hostPath:
            path: /etc/localtime
        {{- end }}
        {{- range $name, $vol := .Values.volumes.persistent }}
        - name: {{ $name }}
          persistentVolumeClaim:
            claimName: {{ $name }}
        {{- end }} 
      {{- end }}