installCRDs: true
serviceType: LoadBalancer
service:
  loadBalancerIP: ${dns_ip}
servers:
  - zones:
      - zone: .
    port: 53
    plugins:
      - name: errors
      # Serves a /health endpoint on :8080, required for livenessProbe
      - name: health
        configBlock: |-
          lameduck 5s
      # Serves a /ready endpoint on :8181, required for readinessProbe
      - name: ready
      # Serves a /metrics endpoint on :9153, required for serviceMonitor
      - name: prometheus
        parameters: 0.0.0.0:9153
      # - name: forward
      #   parameters: . /etc/resolv.conf
      - name: cache
        parameters: 30
      - name: loop
      - name: reload
      - name: loadbalance
      - name: auto
        configBlock: |-
          directory /etc/coredns
zoneFiles:
  %{ for domain in domains }
  - filename: db.${domain}
    domain: ${domain}
    contents: |-
      $ORIGIN ${domain}.
      @	3600 IN	SOA ns.${domain}. root.${domain}. (
              1736115599 ; serial
              7200       ; refresh (2 hours)
              3600       ; retry (1 hour)
              1209600    ; expire (2 weeks)
              3600       ; minimum (1 hour)
              )
        3600 IN NS   ns.${domain}.
        10   IN A    ${gateway_ip}
      *	3600 IN CNAME ${domain}.
  %{ endfor }