apiVersion: v1
kind: Pod
metadata:
  name: helper-pod
  namespace: kube-local-path-storage
spec:
  nodeName: ${node_name}
  priorityClassName: system-node-critical
  tolerations:
    - key: node.kubernetes.io/disk-pressure
      operator: Exists
      effect: NoSchedule
  containers:
    - name: helper-pod
      image: alpine
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: "0.5"
          memory: 512Mi
      securityContext:
        privileged: true
      volumeMounts:
        - name: rootfs
          mountPath: /rootfs
  volumes:
    - name: rootfs
      hostPath:
        path: /
        type: Directory
